// app/layout.jsx
import StoreProvider from "@/providers/StoreProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";
// import StoreProvider from "@/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.jsx (Minimal for the entire app)

export default function MinimalRootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} antialiased min-h-screen flex flex-col`}>
        <StoreProvider>
          <AuthProvider>
            {children}
          </AuthProvider>

        </StoreProvider>
        
      </body>
    </html>
  );
}
